dataset:
  value: "reaction_diffusion.GrayScottMultiFile"
data_path:
  value: "exponax/gray_scott/"
file_prefix:
  value: "data_"
file_count:
  value: 10
image_size:
  value: 64
num_trajectories:
  value: 100
max_traj_per_file:
  value: 2000
model_name:
  value: "T"
lr:
  value: 0.001
lr_embedding_recovery:
  value: 0.001
lr_time_embedding:
  value: 0.001
weight_decay:
  value: 0.01
lr_scheduler:
  value: "cosine"
warmup_ratio:
  value: 0.0
early_stopping_patience:
  value: 0
num_epochs:
  value: 10000000000
batch_size:
  value: 100
inference_batch_size:
  value: 100
single_frame_initialization:
  value: false
max_grad_norm:
  value: 5.0
eta_step_time: # will be real-time updated while running
  value: 0.252
per_data_generation_time:
  value: 0.47509707514047617
per_data_downsample_time:
  value: 0
eval_ndata:
  value: 1000
