dataset:
  value: "fluids.KuramotoSivashinskyMultiFileMultiFrame"
data_path:
  value: "exponax/kuramoto_sivashinsky/"
file_prefix:
  value: "data_"
file_count:
  value: 1
image_size:
  value: 64
num_trajectories:
  value: 100
max_traj_per_file:
  value: 20000
model_name:
  value: "T"
lr:
  value: 0.001
lr_embedding_recovery:
  value: 0.001
lr_time_embedding:
  value: 0.001
weight_decay:
  value: 0.01
lr_scheduler:
  value: "cosine"
warmup_ratio:
  value: 0.0
early_stopping_patience:
  value: 0
num_epochs:
  value: 10000000000
batch_size:
  value: 300
max_grad_norm:
  value: 5.0
eta_step_time:
  value: 0.259
per_data_generation_time:
  value: 0.06673403584957123
per_data_downsample_time:
  value: 0
eval_ndata:
  value: 1000
