# Gray-Scott example config
ndata: 1000
ntest: 100
budget: 100
per_step_time: 0.17
per_data_generation_time: 0.47509707514047617
reduced_resolution: 1
reduced_resolution_t: 1
grid: 64
T_in: 10
T_total: 200
modes: 16
width: 64
n_layers: 16
batch_size: 100
inference_batch_size: 100
single_frame_initialization: false
data_path: ../generated_large_g256_fp32/
save: output_gs
mode: full
use_fork: false
# other model options (optional)
